import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The hand-curated docs sidebar. The API Reference section is populated from
 * the TypeDoc-generated markdown in `docs/api/` (created by `pnpm run gen:api`
 * before every build), so those files must exist when Docusaurus loads.
 */
const sidebars: SidebarsConfig = {
	docsSidebar: [
		"intro",
		"getting-started",
		{
			type: "category",
			label: "Concepts",
			collapsed: false,
			items: [
				"concepts/event-sourcing",
				"concepts/rooms-and-state",
				"concepts/sync",
			],
		},
		{
			type: "category",
			label: "API Reference",
			link: { type: "doc", id: "api/index" },
			items: [{ type: "autogenerated", dirName: "api" }],
		},
	],
};

export default sidebars;
